spring:
  profiles:
    active:
    - local
    devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

---

spring:
  profiles:
  - local
  
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"
      
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/lockwoodmk2?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
        
  session:
    jdbc:
      initialize-schema: always
      

server:
  port: 8080
  tomcat:
     file-encoding: UTF-8
    
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

    jsp:
      init-parameters:
        development: true
    session:
      timeout: 7200
      
  error:
      whitelabel:
        enabled: false
        
mybatis:
  type-aliases-package: com.lcomputerstudy.example.domain
  mapper-locations: mapper/**/*.xml
  
logging:
  config: classpath:logback-spring.xml
  
